version: '3'

services:
  db:
    image: postgres:15.1
    ports:
      - "5432:5432"
    volumes:
      - ./tmp/db:/var/lib/postgres
    environment:
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'password'
  web:
    build: .
    logging:
      driver: fluentd
      options:
        fluentd-address: "localhost:24224"
        fluentd-async-connect: "false"
        tag: "rails_dev"
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - db

  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    logging:
      driver: fluentd
      options:
        fluentd-address: "localhost:24224"
        fluentd-async-connect: "false"
        tag: "nginx"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - public:/app/public
      - tmp:/app/tmp
    ports:
      - "80:80"
    depends_on:
      - web
      - fluent-bit
  fluent-bit:
    image: fluent/fluent-bit
    volumes:
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      - ./parsers.conf:/fluent-bit/etc/parsers.conf
      - ./log:/log:rw
    ports:
      - "24224:24224"
volumes:
  tmp:
  public: