version: '3'

services:
  db:
    image: postgres:15.1
    ports:
      - "5432:5432"
    volumes:
      - ./tmp/db:/var/lib/postgres
    environment:
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'password'
  web:
    build: .
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db