version: '3'

services:
  db:
    image: postgres:15.1
    ports:
      - "5432:5432"
    volumes:
      - ./tmp/db:/var/lib/postgres
    environment:
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'password'
  web:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - db

  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - public:/app/public
      - tmp:/app/tmp
    ports:
      - "80:80"
    depends_on:
      - web
volumes:
  tmp:
  public: